config/routes.rb
Kuroko2::Engine.routes.draw do
  resources :job_definitions, path: 'definitions' do
    get 'page/:page', action: :index, on: :collection, as: 'paged'
    resources :stars, only: %w(create destroy)
    resources :job_instances, path: 'instances', only: %w(index create show destroy) do
      get 'naked', action: :show, on: :member, mode: :naked
      get 'page/:page', action: :index, on: :collection, as: 'paged'
      delete 'force_destroy', action: :force_destroy, on: :member
      resources :tokens, only: %w(index update)
      resources :executions, only: %w(destroy)
      resources :logs, only: %w(index)
      resources :execution_logs, only: %w(index)
    end
    resources :job_schedules, path: 'schedules', only: %w(index create destroy)
    resources :job_suspend_schedules, path: 'suspend_schedules', only: %w(index create destroy)
    resources :job_definition_stats, path: 'stats', only: %w(index) do
      get :memory, action: :memory, on: :collection, defaults: { format: 'json' }
      get :execution_time, action: :execution_time, on: :collection, defaults: { format: 'json' }
    end
    resources :script_revisions, path: 'revisions', only: %w(index)
  end
  resources :users do
    get 'page/:page', action: :index, on: :collection, as: 'paged'
  end

  resources :workers, only: %i(index update)
  resources :job_instances, path: 'instances', only: %w() do
    get :working, action: :working, on: :collection
  end
  resources :executions, only: %i(index)

  resources :job_timelines, only: :index do
    get :dataset, action: :dataset, on: :collection, defaults: { format: 'json' }
  end

  resources :execution_histories, only: :index do
    get :timeline, action: :timeline, on: :collection
    get 'timeline/dataset', action: :dataset, on: :collection, defaults: { format: 'json' }, as: 'dataset'
  end

  get '/sign_in', to: 'sessions#new', as: 'sign_in'
  delete '/sign_out', to: 'sessions#destroy', as: 'sign_out'

  get '/auth/:provider', as: :auth, to: lambda { |_env| [500, {}, 'Never called'] }
  get '/auth/:provider/callback', to: 'sessions#create'

  root 'dashboard#index'
  get '/osd' => 'dashboard#osd', as: :osd

  scope :v1, module: 'api', as: 'api' do
    resources :job_definitions, path: 'definitions', except: %w(new edit) do
      resources :job_instances, path: 'instances', only: %w(show create)
    end

    namespace :stats do
      get :instance
      get :waiting_execution
    end
  end
end

app/models/concerns/kuroko2/table_name_customizable.rb
module Kuroko2
  module TableNameCustomizable
    extend ActiveSupport::Concern

    included do
      self.table_name = self.kuroko2_table_name
    end

    module ClassMethods
      def kuroko2_table_name
        Kuroko2.config.table_name_prefix +
          self.name.gsub(/^Kuroko2::/, '').underscore.pluralize
      end
    end
  end
end

app/models/kuroko2/admin_assignment.rb
class Kuroko2::AdminAssignment < Kuroko2::ApplicationRecord
  include Kuroko2::TableNameCustomizable

  belongs_to :job_definition
  belongs_to :user
end

app/models/kuroko2/api/application_resource.rb
class Kuroko2::Api::ApplicationResource
  include Garage::Representer
  include Garage::Authorizable

  attr_reader :model

  def initialize(model = nil)
    @model = model
  end
end

app/models/kuroko2/api/job_definition_resource.rb
class Kuroko2::Api::JobDefinitionResource < Kuroko2::Api::ApplicationResource
  SIMPLE_PROPERTIES = [
    :id,
    :name,
    :description,
    :script,
    :tags,
    :cron,
    :notify_cancellation,
    :suspended,
    :prevent_multi,
    :slack_channel,
  ]
  SIMPLE_PROPERTIES.each do |name|
    property name
  end
  delegate *SIMPLE_PROPERTIES, :destroy, to: :model

  property def tags
    model.tags.map(&:name)
  end

  property def cron
    model.job_schedules.map(&:cron)
  end

  property def user_id
    model.admins.map(&:id)
  end
end

app/models/kuroko2/api/job_instance_resource.rb
class Kuroko2::Api::JobInstanceResource < Kuroko2::Api::ApplicationResource
  property :id

  property :status

  delegate :id, :status, to: :model
end

app/models/kuroko2/application_record.rb
module Kuroko2
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/kuroko2/execution.rb
class Kuroko2::Execution < Kuroko2::ApplicationRecord
  include Kuroko2::TableNameCustomizable

  DEFAULT_QUEUE = '@default'

  scope :of, ->(token) { where(token: token) }
  scope :with, ->(queue) { where(queue: queue) }
  scope :unstarted, -> { where(started_at: nil) }
  scope :started, -> { where.not(started_at: nil) }

  serialize :context, JSON

  belongs_to :job_definition
  belongs_to :job_instance
  belongs_to :token, optional: true

  has_one :worker

  before_create :set_default_values

  delegate :log_memory_consumption, to: :job_instance

  def completed?
    started_at? && finished_at?
  end

  def success?
    exit_status == 0
  end

  def terminatable?
    pid? && !Kuroko2::ProcessSignal.where(execution_id: id).exists?
  end

  def self.poll(queue = DEFAULT_QUEUE)
    self.transaction do
      unstarted.with(queue).lock.take.tap do |execution|
        execution.touch(:started_at) if execution
      end
    end
  end

  def finish(output:, exit_status:)
    update!(output: output, exit_status: exit_status, finished_at: Time.current)
    job_definition.memory_expectancy.calculate!
  end

  def finish_by_signal(output:, term_signal:)
    update!(output: output, term_signal: term_signal, finished_at: Time.current)
    job_definition.memory_expectancy.calculate!
  end

  private

  def set_default_values
    self.uuid    ||= SecureRandom.uuid
    self.context ||= {}
  end
end

app/models/kuroko2/execution_history.rb
class Kuroko2::ExecutionHistory < Kuroko2::ApplicationRecord
  include Kuroko2::TableNameCustomizable

  belongs_to :job_definition
  belongs_to :job_instance

  scope :ordered, -> { order(started_at: :desc) }
end

app/models/kuroko2/job_definition.rb
class Kuroko2::JobDefinition < Kuroko2::ApplicationRecord
  include Kuroko2::TableNameCustomizable

  # TODO: Drop column in the next release
  self.ignored_columns += %i[hipchat_room]

  module PreventMultiStatus
    NONE = 0
    WORKING_OR_ERROR = 1
    WORKING = 2
    ERROR = 3
  end

  PREVENT_TOKEN_STATUSES = {
    PreventMultiStatus::NONE => [],
    PreventMultiStatus::WORKING_OR_ERROR => [
      Kuroko2::Token::WORKING,
      Kuroko2::Token::FAILURE,
      Kuroko2::Token::CRITICAL
    ],
    PreventMultiStatus::WORKING => [Kuroko2::Token::WORKING],
    PreventMultiStatus::ERROR => [Kuroko2::Token::FAILURE, Kuroko2::Token::CRITICAL],
  }

  self.locking_column = :version

  paginates_per 100

  has_many :admin_assignments, dependent: :destroy
  has_many :admins, -> { active }, through: :admin_assignments, source: :user
  has_many :job_instances, -> { order(:id).reverse_order }
  has_many :job_schedules, dependent: :delete_all
  has_many :job_suspend_schedules, dependent: :delete_all
  has_many :job_definition_tags
  has_many :tags, through: :job_definition_tags
  has_many :revisions, -> { order(id: :desc) }, class_name: 'ScriptRevision', dependent: :destroy
  has_one :memory_expectancy, dependent: :destroy

  before_destroy :confirm_active_instances
  after_initialize :set_default_values
  after_create :create_default_memory_expectancy

  scope :ordered, -> { order(:id) }
  scope :tagged_by, ->(tags) {
    where(
      id: Kuroko2::JobDefinitionTag.
        where(tag_id: Kuroko2::Tag.where(name: tags).pluck(:id)).
        group(:job_definition_id).
        having('COUNT(1) >= ?', tags.size).
        pluck(:job_definition_id)
    )
  }
  scope :search_by, ->(query) {
    column = arel_table
    or_query = column[:name].matches("%#{query}%").or(column[:script].matches("%#{query}%"))

    search_by_tag_definition_ids = Kuroko2::JobDefinitionTag.joins(:tag).
      where("#{Kuroko2::Tag.table_name}.name LIKE ?", "%#{query}%").distinct.pluck(:job_definition_id)

    if search_by_tag_definition_ids.present?
      or_query = or_query.or(column[:id].in(search_by_tag_definition_ids))
    end

    where(or_query)
  }


  validates :name, length: { maximum: 180 }, presence: true
  validates :description, presence: true
  validates :script, presence: true
  validate :script_syntax
  validate :validate_number_of_admins
  validates :hipchat_additional_text, length: { maximum: 180 }
  validates :slack_channel,
    length: { maximum: 81, too_long: ' is too long (maximum is 80 characters without `#` symbol at the head)' },
    format: {
      with: /\A#[^\.\s]+\z/, allow_blank: true,
      message: ' must start with # and must not include any dots or spaces'
    }
  validates :webhook_url, format: { with: /\A#{URI::regexp(%w(http https))}\z/, allow_blank: true }

  def proceed_multi_instance?
    tokens = Kuroko2::Token.where(job_definition_id: self.id)
    (tokens.map(&:status) & PREVENT_TOKEN_STATUSES[self.prevent_multi]).empty?
  end

  def text_tags
    tags.map(&:name).join(',')
  end

  def text_tags=(text_tags)
    self.tags = text_tags.gsub(/[[:blank:]]+/, '').split(/[,、]/).uniq.map do |name|
      Kuroko2::Tag.find_or_create_by(name: name)
    end
  end

  def create_instance(script: nil, launched_by:, token: nil )
    message = "Launched by #{launched_by}"

    if token.present?
      message = "(token #{token.uuid}) #{message}"
    end

    job_instances.create!(script: script, log_message: message)
  end

  def save_and_record_revision(edited_user: nil)
    transaction do
      if save
        record_revision(edited_user: edited_user)
        true
      else
        false
      end
    end
  end

  def update_and_record_revision(attributes, edited_user: nil)
    assign_attributes(attributes)
    transaction do
      if save
        record_revision(edited_user: edited_user)
        true
      else
        false
      end
    end
  end

  private

  def confirm_active_instances
    if Kuroko2::Token.joins(:job_instance).merge(job_instances).exists?
      errors.add(:base, I18n.t('model.job_definition.confirm_active_instances'))
      throw :abort
    end
  end

  def set_default_values
    self.description ||= <<-EOF.strip_heredoc
      An description of the job definition.

      ## Failure Affects
      Affected users, services and/ or business areas.

      ## Workaround
      Choose one of the following:
      - __Retry__ as soon as possible.
      - Make an urgent call to administrator (Job stays in _Error_ state)
      - Do nothing, and let administrator recover later (Job stays in _Error_ state)
      - Ignore error and _Cancel_ the job (No recovery required)

      ## Recovery Procedures
      Describe how to recover from the failure.
    EOF
  end

  def record_revision(edited_user: nil)
    unless revisions.first.try(:script) == script
      revisions.create!(script: script, user: edited_user, changed_at: Time.current)
    end
    nil
  end

  def create_default_memory_expectancy
    create_memory_expectancy! unless memory_expectancy
  end

  def script_syntax
    Kuroko2::Workflow::ScriptParser.new(script).parse

    true
  rescue Kuroko2::Workflow::SyntaxError => e
    errors.add(:base, I18n.t('model.job_definition.script_syntax', reason: e.message))

    false
  rescue Kuroko2::Workflow::AssertionError => e
    errors.add(:base, I18n.t('model.job_definition.validation_error', reason: e.message))

    false
  end

  def validate_number_of_admins
    if self.admins.empty?
      errors.add(:admins, I18n.t('model.job_definition.validate_number_of_admins'))
    end
  end
end

app/models/kuroko2/job_definition_tag.rb
class Kuroko2::JobDefinitionTag < Kuroko2::ApplicationRecord
  include Kuroko2::TableNameCustomizable

  belongs_to :tag
  belongs_to :job_definition
end

app/models/kuroko2/job_instance.rb
class Kuroko2::JobInstance < Kuroko2::ApplicationRecord
  include Kuroko2::TableNameCustomizable

  belongs_to :job_definition

  attr_accessor :log_message

  has_many :logs, dependent: :delete_all do
    def info(message)
      add('INFO', message)
    end

    def warn(message)
      add('WARN', message)
    end

    def error(message)
      add('ERROR', message)
    end

    private
    def add(level, message)
      self.create(level: level, message: message)
    end
  end
  has_many :tokens, dependent: :restrict_with_exception
  has_many :executions, dependent: :restrict_with_exception
  has_one :memory_consumption_log, dependent: :destroy

  before_create :copy_script
  after_create :notify_launch
  after_create :generate_token

  scope :working, -> { where(finished_at: nil, canceled_at: nil) }
  scope :finished, -> { where.not(finished_at: nil) }

  def error?
    working? && error_at?
  end

  def working?
    !finished_at? && !canceled_at?
  end

  def cancelable?
    tokens.first.try(:cancelable?)
  end

  def cancel(by:)
    self.tokens.destroy(*self.tokens)
    self.executions.destroy(*self.executions)
    self.touch(:canceled_at)

    message = "This job was canceled by #{by}."
    self.logs.warn(message)
    Kuroko2.logger.warn(message)

    Kuroko2::Workflow::Notifier.notify(:cancellation, self) if job_definition.hipchat_notify_finished?
  end

  # Log given value if it is greater than stored one.
  # This logging is not so important that we can ignore race condition,
  # so we use `#update` and `#create_association` without bang here.
  # @param [Intger] value
  def log_memory_consumption(value)
    if memory_consumption_log
      max = [value, memory_consumption_log.value].max
      memory_consumption_log.update(value: max)
    else
      create_memory_consumption_log(value: value)
    end
  end

  def execution_minutes
    (((error_at || canceled_at || finished_at || Time.current) - created_at).to_f / 60).round(2)
  end

  def status
    if finished_at?
      'success'
    elsif canceled_at?
      'canceled'
    elsif error_at?
      'error'
    else
      'working'
    end
  end

  private

  def copy_script
    self.script = job_definition.try(:script) if self.script.blank?
  end

  def notify_launch
    if log_message
      Kuroko2.logger.info(log_message)
      self.logs.info(log_message)
      Kuroko2::Workflow::Notifier.notify(:launch, self)
    end
  end

  def generate_token
    unless self.job_definition
      raise 'No parent association is found'
    end

    if job_definition.proceed_multi_instance?
      self.tokens << Kuroko2::Token.new do |token|
        definition = self.job_definition

        token.job_definition         = definition
        token.job_definition_version = definition.version
        token.script                 = self.script
        token.context                = {
          meta: {
            launched_time:       Time.current,
            job_definition_id:   definition.id,
            job_definition_name: definition.name,
            job_instance_id:     id,
          }
        }
      end
    else
      self.touch(:canceled_at)

      message = 'This job was canceled because there is already a working or erred job instance.'
      self.logs.warn(message)
      Kuroko2.logger.warn(message)

      Kuroko2::Workflow::Notifier.notify(:cancellation, self) if job_definition.notify_cancellation
    end
  end
end

app/models/kuroko2/job_suspend_schedule.rb
class Kuroko2::JobSuspendSchedule < Kuroko2::ApplicationRecord
  include Kuroko2::TableNameCustomizable

  belongs_to :job_definition

  validates :cron, format: { with: Kuroko2::JobSchedule::CRON_FORMAT }, uniqueness: { scope: :job_definition_id, case_sensitive: true }
  validate :validate_cron_schedule

  def suspend_times(time_from, time_to)
    it = Chrono::Iterator.new(cron, now: time_from - 1)
    suspend_times = []

    loop do
      next_time = it.next
      if next_time <= time_to
        suspend_times << next_time
      else
        break
      end
    end

    suspend_times.map(&:in_time_zone)
  end

  private

  def validate_cron_schedule
    if Kuroko2::JobSchedule::CRON_FORMAT === cron
      suspend_schedule = Chrono::Schedule.new(cron)
      if job_definition.job_schedules.empty?
        errors.add(:cron, "needs job schedules")
      else
        schedule = job_definition.job_schedules.each_with_object({}) do |launch_schedule_model, h|
          launch_schedule = Chrono::Schedule.new(launch_schedule_model.cron)
          Kuroko2::JobSchedule::CHRONO_SCHEDULE_METHODS.each do |method|
            h[method] ||= []

            suspend_schedule_list = suspend_schedule.public_send(method)
            # https://linux.die.net/man/5/crontab
            # > Note: The day of a command's execution can be specified by two fields
            # >  day of month, and day of week. If both fields are restricted (ie, aren't *),
            # >  the command will be run when either field matches the current time.
            # >  For example, "30 4 1,15 * 5" would cause a command to be run at 4:30 am
            # >  on the 1st and 15th of each month, plus every Friday.
            if launch_schedule.wdays? && launch_schedule.days?
              if (method == :wdays && suspend_schedule.wdays? && !suspend_schedule.days?) || (method == :days && !suspend_schedule.wdays? && suspend_schedule.days?)
                suspend_schedule_list = []
              end
            end

            h[method] |= launch_schedule.public_send(method) - suspend_schedule_list
          end
        end

        if schedule.values.all?(&:empty?)
          errors.add(:cron, "suspends all launched schedules")
        end
      end
    end
  rescue Chrono::Fields::Base::InvalidField => e
    errors.add(:cron, "has invalid field: #{e.message}")
  end
end

app/models/kuroko2/log.rb
class Kuroko2::Log < Kuroko2::ApplicationRecord
  include Kuroko2::TableNameCustomizable
end

app/models/kuroko2/star.rb
class Kuroko2::Star < Kuroko2::ApplicationRecord
  include Kuroko2::TableNameCustomizable

  belongs_to :user
  belongs_to :job_definition
end

app/views/kuroko2/job_definitions/_alert.html.slim
- if @definition.errors.any?
  .alert.alert-danger
    i.fa.fa-ban
    h4 #{pluralize(@definition.errors.count, "error")} prohibited this job definition from being saved:
    ul
    - @definition.errors.full_messages.each do |message|
      li= message

app/views/kuroko2/job_definitions/_form.html.slim
.box-body
  = form_for @definition, html: { role: 'form' } do |form|
    .row.form-group
      .col-md-4
        = form.label :name
        = form.text_field :name, class: 'form-control'
    .form-group
      = form.label :description
      = form.text_area :description, class: 'form-control', rows: 10
    .form-group
      label Administrators
      = collection_select(:admin_assignments, :user_id, Kuroko2::User.active.order(:name).all, :id, :name,
                          { selected: @definition.admins.map(&:id), include_blank: false },
                          { multiple: true, class: 'form-control' })

    .form-group
      = form.label :script
      = form.text_area :script, class: 'form-control script-input', rows: 6

    .checkbox
      label
        = form.check_box :api_allowed
        ' Allow API execution of this job

    label Notification
    .form-group
      label Slack Channel
      = form.text_field :slack_channel, class: 'form-control', placeholder: '#slack-channel'
    .form-group
      label Webhook URL
      = form.text_field :webhook_url, class: 'form-control', placeholder: 'http://example.com/webhook/endpoint'

    .checkbox
      label
        = form.check_box :hipchat_notify_finished
        ' Notify all event to Slack/Webhook

    .checkbox
      label
        = form.check_box :notify_cancellation
        ' Notify administrators when the job is cancelled by system.

    .form-group
      label for='hipchat_additional_text'
        'Failure notification text
      = form.text_field :hipchat_additional_text, class: 'form-control', placeholder: '@YourName @your-name'

    .form-group
      label Next Job Execution
      .radio
        label
          = form.radio_button :prevent_multi, 0
          ' Always launch next job (allow parallel execution)
      .radio
        label
          = form.radio_button :prevent_multi, 1
          ' Prevent if current job is WORKING or ERROR
      .radio
        label
          = form.radio_button :prevent_multi, 2
          ' Prevent if current job is WORKING
      .radio
        label
          = form.radio_button :prevent_multi, 3
          ' Prevent if current job is ERROR
    .form-group
      label Job Scheduling
      .radio
        label
          = form.radio_button :suspended, false
          b> Active:
          ' the job will be scheduled to run.
      .radio
        label
          = form.radio_button :suspended, true
          b> Suspend:
          ' the job will NOT be scheduled to run.

    .form-group
      label Tags
      .form-group
        = form.text_field :text_tags, class: 'form-control', placeholder: 'Tag1,Tag2,Tag3'

    .box-footer
      .row
        .col-md-3.col-md-offset-9
          = form.submit class: 'btn btn-default btn-block'

app/views/kuroko2/job_definitions/_list.html.slim
- if definitions.any?
  table.table.table-hover.sortable
    thead
      tr
        th #
        th.col-md-3 Name
        th.col-md-2 Next Job
        th.col-md-1 Latest Status
        th.col-md-5 data-defaultsort='disabled' Tags / Description
        th.col-md-1 data-defaultsort='disabled' &nbsp;
    tbody
      - for definition in definitions
        tr
          td= definition.id
          td.no-decorate
            - if definition.suspended
              span.label.label-warning.spacer-right-3 SUSPENDED
            = link_to definition.name, definition
          - if !definition.suspended? && !definition.job_schedules.empty?
            - next_job_schedule = definition.job_schedules.map(&:next).min
            - if next_job_schedule
              td data-value=next_job_schedule.to_i = l(next_job_schedule, format: :short)
            - else
              td data-value="9999999999" --
          - else
            td data-value="9999999999" --
          td= labeled_status(definition.job_instances.take)
          td
            - definition.tags.each do |tag|
              =link_to tag.name, { 'tag': [tag.name] }, class: 'label label-default spacer-right-3'
            = first_line(definition.description)
          td
            = link_to definition, class: 'btn btn-sm btn-default' do
              i class="fa fa-chevron-right"
              | &nbsp;
              span class="small" View Details

- else
  .text-muted.well.well-sm.no-shadow There are no favorite job definitions.

app/views/kuroko2/job_definitions/_search_results.html.slim
- @scope = definitions

.box-header
  - if input_tags.present?
    h3.box-title All Job Definitions tagged by #{input_tags.join(', ')}
  - else
    h3.box-title All Job Definitions

  .row
    #job_search.col-md-4.col-md-offset-8
      = form_tag job_definitions_path, method: :get, role: 'form', remote: true do
        .form-group
          .input-group
            = search_field_tag :q, params[:q], class: 'form-control', placeholder: 'Search'
            - for tag in input_tags
              = hidden_field_tag 'tag[]', tag
            span.input-group-btn
              button.btn.btn-flat
                i.fa.fa-search
#definitions.box-body
  - if definitions.present?
    table.table.table-hover
      tbody
        tr
          th &nbsp;
          th #
          th.col-md-3 Name
          th.col-md-3 Administrators
          th.col-md-5 Tags / Description
          th.col-md-1 &nbsp;
        - for definition in definitions
          tr
            td
              span.star-holder
                = star_link_for(definition)
            td= definition.id
            td.no-decorate
              - if definition.suspended
                span.label.label-warning.spacer-right-3 SUSPENDED
              = link_to definition.name, definition
            td.no-decorate
              - definition.admins.each do |user|
                = link_to user.name, user_path(user)
                br
            td
              - definition.tags.each do |tag|
                =link_to tag.name, job_definitions_path('tag': [tag.name]), class: 'label label-default spacer-right-3'
              = first_line(definition.description)
            td
              = link_to definition, class: 'btn btn-sm btn-default' do
                i class="fa fa-chevron-right"
                | &nbsp;
                span class="small" View Details

  - else
    - if params[:q].present?
      .text-muted.well.well-sm.no-shadow No results found for the query.
    - else
      .text-muted.well.well-sm.no-shadow There are no job definitions yet.
.box-footer#pagination
  = paginate definitions, theme: 'list', remote: true

app/views/kuroko2/job_definitions/edit.html.slim
- content_for :title, "##{@definition.id} #{@definition.name} « Job Definitions"
- content_for :content_title, "##{@definition.id} #{@definition.name}"

- content_for :breadcrumb do
  ol.breadcrumb
    li= link_to raw('<i class="fa fa-database"></i> Job Definitions'), job_definitions_path
    li= link_to 'Details', @definition
    li.active Edit

= render 'alert'

.box.box-solid
  .box-body
    h3.box-title Edit Job Definition
    = render 'form'

app/views/kuroko2/job_definitions/index.html.slim
- content_for :title, 'Job Definitions'
- content_for :content_title do
  <i class="fa fa-database"></i> Job Definitions

.row
  .col-md-9
    .box#search_results
      = render 'search_results', { definitions: @definitions, input_tags: @input_tags, params: params }

  .col-md-3
    .box#tags
      = render 'kuroko2/shared/taglist', { input_tags: @input_tags, related_tags: @related_tags, add_params: { q: params[:q] } }

app/views/kuroko2/job_definitions/new.html.slim
- content_for :title, 'New Job Definition'
- content_for :content_title do
  <i class="fa fa-database"></i> New Job Definition

- content_for :breadcrumb do
  ol.breadcrumb
    li= link_to raw('<i class="fa fa-database"></i> Job Definitions'), job_definitions_path
    li.active New Job Definition

= render 'alert'

.box.box-solid
  = render 'form'

app/views/kuroko2/job_definitions/show.html.slim
- content_for :title, "##{@definition.id} #{@definition.name} « Job Definitions"
- content_for :content_title, "Job Definition Details"

- content_for :breadcrumb do
  ol.breadcrumb
    li= link_to raw('<i class="fa fa-database"></i> Job Definitions'), job_definitions_path
    li.active Details

.row
  .col-md-7
    .box
      .box-header
        h2.box-title.star-holder #{star_link_for(@definition)} ##{@definition.id} #{@definition.name}
        - if @definition.suspended?
          .box-tools.pull-right
            span.label.label-warning SUSPENDED
      .box-body
        .description= markdown_format @definition.description

        h4= 'Tags'
        - for tag in @definition.tags
          =link_to tag.name, job_definitions_path(tag: [tag.name]), class: 'label label-default spacer-right-3'

        h3= 'Administrator'.pluralize(@definition.admins.count)
        ul.media-list
          - for admin in @definition.admins
            li.media
              span.pull-left
                img.img-rounded src="#{admin.image}" height='20' width='20'
              .media-body.no-decorate= link_to admin.name, user_path(admin)
        h3 Script
        pre.kuroko-script= format_kuroko_script(@definition.script)

        = link_to 'Show script revisions', job_definition_script_revisions_path(@definition)
        br

        'API execution allowed: #{@definition.api_allowed ? 'Yes' : 'No'}

        h4 Estimated Memory Consumption
        p
          strong #{number_with_delimiter(@definition.memory_expectancy.expected_value)} Kbytes

        h3 Options
        h4 Notification
        ul
          - if @definition.slack_channel.present?
            - if @definition.hipchat_notify_finished?
              li
                'Notify all event to Slack/Webhook
                ul
                  li webhook url: #{@definition.webhook_url}
                  li slack channel: #{@definition.slack_channel}
                  - if @definition.hipchat_additional_text
                    li Failure notification text: #{@definition.hipchat_additional_text}
            - else
              li
                'Notify failure event to Slack/Webhook
                ul
                  li webhook url: #{@definition.webhook_url}
                  li slack channel: #{@definition.slack_channel}
                  - if @definition.hipchat_additional_text
                    li Failure notification text: #{@definition.hipchat_additional_text}

          - if @definition.notify_cancellation
            li Notify administrators when the job is cancelled by system.

          - if !@definition.slack_channel && !@definition.notify_cancellation
            li None

        h4 Next Job Execution
        ul
          - case @definition.prevent_multi
          - when 0
            li Always launch next job (allow parallel execution)
          - when 1
            li Prevent if current job is WORKING or ERROR
          - when 2
            li Prevent if current job is WORKING
          - when 3
            li Prevent if current job is ERROR

      .box-footer
        .row
          .col-md-4
            = link_to 'Edit Job definition', edit_job_definition_path(@definition), class: 'btn btn-default btn-block', role: 'button'
          .col-md-4
            = link_to 'Duplicate Job definition', new_job_definition_path(dup_from: @definition.id), class: 'btn btn-default btn-block', role: 'button'
          .col-md-4
            = link_to 'Destroy Job definition', @definition, method: :delete, class: 'btn btn-default btn-block', role: 'button', data: { confirm: 'Are you sure?' }
  .col-md-5#schedules-holder
    = render template: 'kuroko2/job_schedules/index'
  .col-md-5#suspend-schedules-holder
    = render template: 'kuroko2/job_suspend_schedules/index'
  .col-md-5#instances-holder
    = render template: 'kuroko2/job_instances/index'